site_name: SiC Blog Mkdocs

## Added material on 2026-04-26
theme:
  name: material

## Added search and tags on 2026-04-26
plugins:
  - search
  - tags:
      tags_file: tags.md
  - callouts
  - obsidian-bridge

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
